# Generated by Django 4.0.4 on 2022-06-12 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customereName', models.CharField(max_length=255)),
                ('customerEmail', models.EmailField(max_length=255, unique=True)),
                ('customerPhone', models.IntegerField()),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieTitle', models.CharField(max_length=255)),
                ('movieDate', models.DateField()),
                ('movieTime', models.DateTimeField()),
                ('movieDescription', models.TextField()),
                ('movieRating', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showingTime', models.DateTimeField()),
                ('showingDate', models.DateField()),
                ('movieId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bluemouseapp.movie')),
            ],
            options={
                'db_table': 'showing',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketPurchaseDate', models.DateField()),
                ('ticketPurchaseTime', models.DateTimeField()),
                ('ticketPurchasePrice', models.DecimalField(decimal_places=2, max_digits=19)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bluemouseapp.customer')),
                ('showingId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bluemouseapp.showing')),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
    ]
