# Generated by Django 4.0.5 on 2022-06-17 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluemouseapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customereName',
            new_name='customerName',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movieDate',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movieTime',
        ),
    ]
